;
; File generated by cc65 v 2.18 - Git f8be35b
;
	.fopt		compiler,"cc65 v 2.18 - Git f8be35b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_printf
	.export		_someVar
	.export		_SomeMethod

.segment	"RODATA"

L0008:
	.byte	$25,$30,$34,$44,$3A,$00

.segment	"BSS"

_someVar:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ SomeMethod (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_SomeMethod: near

.segment	"CODE"

	lda     #<(L0008)
	ldx     #>(L0008)
	jsr     pushax
	lda     #$01
	jsr     pusha0
	ldy     #$04
	jmp     _printf

.endproc

