;
; File generated by cc65 v 2.18 - Git f8be35b
;
	.fopt		compiler,"cc65 v 2.18 - Git f8be35b"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		__lineBuffer
	.export		__workingLineBuffer
	.export		__editorLines
	.export		__editorLinesCapacity
	.export		__editorLineSegments
	.export		__firstFreeSegment
	.export		__maxLineSegment
	.export		__textPos
	.export		__screenSize
	.export		__statusBarLineNo
	.export		__debugLineNo
	.export		__maxLine
	.export		_ClearScreen
	.export		_DrawWindow

.segment	"BSS"

__lineBuffer:
	.res	160,$00
__workingLineBuffer:
	.res	160,$00
__editorLines:
	.res	2,$00
__editorLinesCapacity:
	.res	2,$00
__editorLineSegments:
	.res	2,$00
__firstFreeSegment:
	.res	2,$00
__maxLineSegment:
	.res	2,$00
__textPos:
	.res	6,$00
__screenSize:
	.res	6,$00
__statusBarLineNo:
	.res	1,$00
__debugLineNo:
	.res	1,$00
__maxLine:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ ClearScreen (unsigned char, unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ClearScreen: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	lda     __screenSize
	jsr     pusha0
	ldy     #$08
	lda     (sp),y
	jsr     tosumula0
	sta     ptr1
	txa
	clc
	adc     #$04
	sta     ptr1+1
	ldy     #$07
	lda     (sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0023
	inx
L0023:	ldy     #$02
	jsr     staxysp
	lda     #$00
	tay
	sta     (sp),y
	tax
L0025:	lda     (sp),y
	ldy     #$04
	cmp     (sp),y
	bcs     L000D
	txa
	ldy     #$01
L0029:	sta     (sp),y
	ldy     #$05
	cmp     (sp),y
	bcs     L0028
	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L001D
	inx
L001D:	jsr     staxysp
	lda     #$20
	ldy     #$00
	sta     (regsave),y
	iny
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$01
	jmp     L0029
L0028:	lda     __screenSize
	sec
	ldy     #$07
	sbc     (sp),y
	ldy     #$02
	jsr     addeqysp
	ldy     #$00
	ldx     #$00
	lda     (sp),y
	clc
	adc     #$01
	sta     (sp),y
	jmp     L0025
L000D:	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ DrawWindow (unsigned char, unsigned char, unsigned char, unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DrawWindow: near

.segment	"CODE"

	jsr     pushax
	jmp     incsp6

.endproc

